#%RAML 1.0
title: shs-new-app
baseUri: https://api-test.aws.transformco.com/shs-new-app/v1/
version: "1.0"
mediaType: application/json

uses:
  SecuritySchemes: exchange_modules/a0816b18-ae2e-49b8-945f-d0e5ce7c9732/shs-standard-security-schemes/1.0.0/shs-standard-security-schemes.raml
  HealthCheck: exchange_modules/a0816b18-ae2e-49b8-945f-d0e5ce7c9732/shs-health-check/1.0.0/shs-health-check.raml
  #Change system-api to process-api or experience-api depending on what type of api are you doing.
  StandardErrors: exchange_modules/a0816b18-ae2e-49b8-945f-d0e5ce7c9732/shs-standard-rest-system-api-errors/1.0.0/shs-rest-system-api-errors.raml
  
  Headers: libraries/headers.raml

securedBy: [ SecuritySchemes.clientIdEnforcement ]

/:
  type: HealthCheck.check
  is: [ StandardErrors.errorHandler ]

/serviceOrder:
  is:
    - StandardErrors.errorHandler
    - Headers.hashHeaders
  
  /{uri}:   
    description: 
    displayName: Send Order Status
    post:
      body:
        application/json:
        application/xml:
      responses:
        200:
          body:
            application/json:
            application/xml:
         